# This is only used to build an binary, which will be used by
# the main Dockerfile.
#
# Main reason for doing this, is because most the tools installed
# here are not required by the binary so ends up wasting space.
#
# Yasser

FROM golang:1.8.1-alpine
MAINTAINER Tim Ehlers "ehlerts@gmail.com"
EXPOSE 2003 2004 8081

RUN mkdir /localmount

RUN apk add --no-cache git
RUN go get github.com/graphite-ng/carbon-relay-ng/...
